# Generated by Django 6.0 on 2025-12-13 18:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('movement_type', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Saída'), ('ADJUST', 'Ajuste')], max_length=10, verbose_name='Tipo de Movimento')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Motivo')),
                ('reference_type', models.CharField(choices=[('PURCHASE', 'Compra'), ('SALE', 'Venda'), ('SERVICE_ORDER', 'Ordem de Serviço'), ('MANUAL', 'Manual')], default='MANUAL', max_length=20, verbose_name='Origem da Movimentação')),
                ('reference_id', models.UUIDField(blank=True, null=True, verbose_name='ID da Referência')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='catalog.product', verbose_name='Produto')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='stock.warehouse', verbose_name='Depósito')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-created_at'],
            },
        ),
    ]
