# Generated by Django 6.0.2 on 2026-02-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='new_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nova Quantidade (Ajuste)'),
        ),
    ]
